#!/bin/bash

set -ex

# This shouldn't be in the Dockerfile or containers built from the same image
# will have the same credentials.
mkdir -p $HOME/.bitcoin1
mkdir -p $HOME/.bitcoin2

echo "Creating bitcoin.conf's"

    cat <<EOF > $HOME/.bitcoin1/bitcoin.conf
regtest=1
disablewallet=0
server=1
maxmempool=2000
rpcport=8332
onlynet=ipv4
txindex=1
printtoconsole=${PRINTTOCONSOLE1:-1}
rpcuser=${RPCUSER:-bitcoinrpc}
rpcpassword=${RPCPASSWORD:-`dd if=/dev/urandom bs=33 count=1 2>/dev/null | base64`}
checkmempool=1
debug=1
rpcallowip=0.0.0.0/0
EOF

    cat <<EOF > $HOME/.bitcoin2/bitcoin.conf
regtest=1
disablewallet=0
server=1
listen=0
maxmempool=2000
rpcport=8334
printtoconsole=1
onlynet=ipv4
txindex=1
rpcuser=${RPCUSER:-bitcoinrpc}
rpcpassword=${RPCPASSWORD:-`dd if=/dev/urandom bs=33 count=1 2>/dev/null | base64`}
connect=127.0.0.1:18444
checkmempool=1
debug=1
rpcallowip=0.0.0.0/0
EOF


echo "Initialization completed successfully"

exec nohup bitcoind -datadir=$HOME/.bitcoin1 "${args[@]}" | sed  's/^/[bitcoin1] /' & > bitcoind1.out \
    && bitcoind -datadir=$HOME/.bitcoin2 "${args[@]}" | sed  's/^/[bitcoin2] /'
